### ISSUE TITLE
Extension button stays disabled although debug info is enabled

### ISSUE THREAD

**Issue by dradovic** [ryanoglesby08/ng-inspect-watchers#1]
I'm trying to get your Chrome app working but I just can't get the Page Action to be shown. I made sure that debug info is enabled. Looking at the DOM, I see element with `ng-scope` and `ng-isolate-scope`. What could be the reason the Page Action not shown?

BTW, I'm using Angular 1.4.4 and Chrome 51.0.

**Comment by ryanoglesby08** [comment]
Hi dradovic, thanks for trying out my extension. I'm testing version 1.0.1 of the extension on https://angularjs.org/ with Chrome 49.0 right now (my Chrome thinks its up to date). It seems to be working with those conditions.

Maybe you are having trouble just finding the icon becuase the UI of Chrome has changed recently:
Chrome recently changed the UI of its extensions icons, so you won't see them in the address box like you used to. Lots of upset folks too: https://bugs.chromium.org/p/chromium/issues/detail?id=572522. Instead, they may appear in the toolbar, or in the settings menu.

The Page Action icon for ng-inspect-watchers may be hidden in the Settings drop down menu. If you right-click on that, you can choose to "Keep in Toolbar", which will pin the extension icon to the Toolbar, otherwise, it will stay in the drop down menu.

Are you able to find the extension icons in the settings drop down menu? Does the extension work on https://angularjs.org/? If not I can dig in deeper.

**Comment by dradovic** [comment]
Hi! First of all, thanks for providing and sharing this wonderful extension!
I just had a second look. The extension shows up in the toolbar right next to the URL (I guess that makes it look like a Browser Action again?).
When I browse https://angularjs.org/, the button becomes enabled and I can activate the extension. However, on my page the button unfortunately stays disabled. So, still I haven't found a way to use the extensions.

**Comment by dradovic** [comment]
How do you analyze the DOM to make the enabling? Are you looking for a specific element/attribute?

**Comment by ryanoglesby08** [comment]
> The extension shows up in the toolbar right next to the URL (I guess that makes it look like a Browser Action again?).

Yeah, the new UI is not very clear. Both Browser Actions and Page Actions show up the same place. And the greyed out thing that happens now is not usable at all.

> How do you analyze the DOM to make the enabling? Are you looking for a specific element/attribute?

Yes. It relies on the presence of `ng-scope` or `ng-isolate-scope` CSS class names on elements to enable the Page Action. Once the Page Action is enabled and you click it, it also needs the `window.angular` object. (https://docs.angularjs.org/guide/css-styling)

Is there any error or anything in the console log?
Is the app you are trying to use the extension on public? I could try to take a look if so.

**Comment by dradovic** [comment]
There's nothing in the console log. Unfortunately, this is a non-public enterprise web-app I'm trying it to run on. But here's a screenshot of the DOM: https://snag.gy/UPbW0a.jpg

Any idea why it's not picking up the `ng-scope` or `ng-isolate-scope` attributes? Can they be on any element?

**Comment by ryanoglesby08** [comment]
Trying to reproduce your set up locally. In general, trying it out with `ng-app` and `ng-controller` both on the `html` element seems to work fine. (btw, also now on Angular 1.4.3 & Chrome 51).

Are you using the Manual Initialization process (calling angular.bootstrap yourself) described here? https://docs.angularjs.org/guide/bootstrap#manual-initialization. Since you have an `ng-app` it doesn't seem like you do but wanted to make sure. If so, I did manage to get things to break a bit when using that in a specific way. The Page Action became clickable, but I couldn't use it.
- Do you have any other extensions, especially Angular extensions such as Batarang enabled? Maybe something else is interfering?
- Just to double confirm, does the Page Action ever turn red for you when clicking it on your app? The Page Action could turn red, but then the extension still not work. There are two pieces of code, the code that turns on the Page Action, and the actual extension code.

**Comment by ryanoglesby08** [comment]
Since I'm not yet able to reproduce, and can't access your app, you could also try debugging a little bit too. The extension is all open source.

First thing you should check would be the "background page":
1. open chrome://extneions
2. Turn on "Developer mode"
3. Scroll to the extension and open the background page: "Inspect views: background page"
4. Look for any messages or errors there as you try to use the extension.

You can also just fork it from github and play with it locally. Obviously that will require a bit more of an investment from you.

**Comment by dradovic** [comment]
> Are you using the Manual Initialization process?

No.

> Do you have any other extensions, especially Angular extensions such as Batarang enabled?

Yes. ng-inspector and Angular Perfomance. Then I tried yours. Then I installed Batarang and removed it again. But your extension works on the Angular site itself. The toolbar button gets enabled and when I click it, I get red balloons showing the number of watches when hovering over the page. So there must be something wrong with my page, I guess. On my page, the toolbar button just doesn't get enabled.

**Comment by dradovic** [comment]
Aaah, I've found it! It was the "incognito mode" where it doesn't work! When looking at the page in normal mode it works! I wonder why? The "allow in incognito" checkbox is checked.

Anyways, I can work with your extension now. Delicious! Thanks for your support!

**Comment by ryanoglesby08** [comment]
haha well glad you found it! Not sure why it doesn't work in Incognito mode, I had never actually tried that before. I think a lot of extensions don't work properly in Incognito mode as Chrome probably locks down many APIs.
